### ISSUE TITLE
Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings

### ISSUE THREAD

**Issue by NathHorrigan** [GoldenOwlAsia/react-native-twitter-signin#92]
The library is working perfect on Android but on iOS when I trigger function nothing happens and this error is spit into logs:

`Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings`

Any Idea what I need to do to fix?

**Comment by juanlet** [comment]
Hey, you need to define the callback url on your twitter developer account, I had this trouble too and that solved it...let me know how it goes

**Comment by NathHorrigan** [comment]
Thanks for the suggestion - I've already added the firebase URL but it's still causing this error.

**Comment by juanlet** [comment]
Did you add the ios platform in forebase console?...you are close...I can assure you it works fine

**Comment by NathHorrigan** [comment]
Yep. Already added in the Firebase console as I have Google auth working on both platforms (with Twitter working on Android)

**Comment by juanlet** [comment]
Sorry, just saw this. I think your problem might be on your AppDelegate.m, let me give you mine which is an app where twitter signin is working in ios. Let me know how it goes:

```
#import "AppDelegate.h"
#import <React/RCTBundleURLProvider.h>
#import <FBSDKCoreKit/FBSDKCoreKit.h>

// **********************************************
// *** DON'T MISS: THE NEXT LINE IS IMPORTANT ***
// **********************************************


// IMPORTANT: if you're getting an Xcode error that RCCManager.h isn't found, you've probably ran "npm install"
// with npm ver 2. You'll need to "npm install" with npm 3 (see https://github.com/wix/react-native-navigation/issues/1)

#import <Firebase.h>
#import "RCCManager.h"
#import <TwitterKit/TwitterKit.h>

#import <React/RCTRootView.h>


@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];

  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];
  
 [[Twitter sharedInstance] startWithConsumerKey:@"dasdasdasda31231" consumerSecret:@"faadasdasdasdasdasddasdas"];


  NSURL *jsCodeLocation;
#ifdef DEBUG
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
  
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  self.window.backgroundColor = [UIColor whiteColor];
  [[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation launchOptions:launchOptions];
  
  return YES;
}

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<NSString *,id> *)options {
  
  BOOL handled = [[FBSDKApplicationDelegate sharedInstance] application:application
                                                                openURL:url
                                                      sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                                                             annotation:options[UIApplicationOpenURLOptionsAnnotationKey]
                  ];

  BOOL handledT = [[Twitter sharedInstance] application:application openURL:url options:options];
  // Add any custom logic here.
  return handled || handledT;
}


- (void)applicationDidBecomeActive:(UIApplication *)application {
  [FBSDKAppEvents activateApp];
}

@end

```
Just in case my podfile:

**Comment by NathHorrigan** [comment]
@juanlet Thanks for the support with this!

Here is the error I get when clicking Twitter Button:
```
[TwitterKit] did encounter error with message "Error obtaining user auth token.": Error Domain=TWTRLogInErrorDomain Code=-1 "<?xml version="1.0" encoding="UTF-8"?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>" UserInfo={NSLocalizedDescription=<?xml version="1.0" encoding="UTF-8"?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>}
```

AppDelegate.m:
```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>
#import "SplashScreen.h"
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import "RNFirebaseLinks.h"
#import "RNFirebaseMessaging.h"
#import "RNFirebaseNotifications.h"
#import <TwitterKit/TwitterKit.h>
#import "RNTwitterSignIn.h"


@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<NSString *, id> *)options {
  
  [[RNFirebaseLinks instance] application:application openURL:url options:options];
  
  BOOL handledF = [[FBSDKApplicationDelegate sharedInstance]
                  application:application
                  openURL:url
                  sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                  annotation:options[UIApplicationOpenURLOptionsAnnotationKey]];
  
  BOOL handledT = [[Twitter sharedInstance] application:application openURL:url options:options];

  return handledF || handledT;
  
}

- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray *))restorationHandler {
     return [[RNFirebaseLinks instance] application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
  [FBSDKAppEvents activateApp];
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  [[FBSDKApplicationDelegate sharedInstance]
      application:application
      didFinishLaunchingWithOptions:launchOptions];
  [[Twitter sharedInstance] startWithConsumerKey:@"QlOBbfwwCb8AkdTsp0BD8LuxP" consumerSecret:@"0at2jZPNpVWSQFH0ZXKXERNqZUZJwa8cuLpNXQiIHcmOhfFHqu"];
  
  NSURL *jsCodeLocation;
  
  
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"CoinTower"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
  
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [FIROptions defaultOptions].deepLinkURLScheme = @"io.github.cointower";
  [FIRApp configure];
  [RNFirebaseNotifications configure];
  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
  [SplashScreen show];
  return YES;
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  
  return
    [[FBSDKApplicationDelegate sharedInstance]
     application:application
     openURL:url
     sourceApplication:sourceApplication
     annotation:annotation
     ];
}

- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [[RNFirebaseNotifications instance] didReceiveLocalNotification:notification];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
  [[RNFirebaseMessaging instance] didRegisterUserNotificationSettings:notificationSettings];
}
@end

```

**Comment by NathHorrigan** [comment]
Hmmmm ok.

Here's my Info.plis:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>Coin Tower</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.13.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.RANDOM</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>twitterkit-random</string>
				<string>fbRANDOM</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>cointower</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>io.github.cointower</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>30</string>
	<key>FacebookAppID</key>
	<string>randomAppId</string>
	<key>FacebookDisplayName</key>
	<string>Cointower</string>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fbapi</string>
		<string>fb-messenger-share-api</string>
		<string>fbauth2</string>
		<string>fbapi20150629</string>
		<string>fb-messenger-api</string>
		<string>fbshareextension</string>
		<string>twitter</string>
		<string>twitterauth</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string/>
	<key>UIAppFonts</key>
	<array>
		<string>Entypo.ttf</string>
		<string>EvilIcons.ttf</string>
		<string>Feather.ttf</string>
		<string>FontAwesome.ttf</string>
		<string>Foundation.ttf</string>
		<string>Ionicons.ttf</string>
		<string>MaterialCommunityIcons.ttf</string>
		<string>MaterialIcons.ttf</string>
		<string>Octicons.ttf</string>
		<string>SimpleLineIcons.ttf</string>
		<string>Zocial.ttf</string>
		<string>PeaceSans.ttf</string>
	</array>
	<key>UIBackgroundModes</key>
	<array>
		<string>remote-notification</string>
	</array>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UIStatusBarStyle</key>
	<string>UIStatusBarStyleLightContent</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>
```

**Comment by NathHorrigan** [comment]
@juanlet  Any ideas on what's wrong here?

**Comment by juanlet** [comment]
Yes, you are duplicating keys inside CFBundleURLTypes, you need to unify that.....the correct key for URLs would be something like this, play with that until it detects the urls correctly since this is clearly why is not detecting the twitter url
```

<key>CFBundleURLTypes</key>
	<array>
		<dict>
		 <key>CFBundleTypeRole</key>
              	<string>Editor</string>     
			<key>CFBundleURLName</key>
			    <string>cointower</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>io.github.cointower</string>
                <string>com.googleusercontent.apps.RANDOM</string>
                <string>twitterkit-random</string>
				<string>fbRANDOM</string>
			</array>
		</dict>
	</array>
```

**Comment by NathHorrigan** [comment]
@juanlet Thanks! I just did this but now I'm getting this error:
```
'Attempt made to Log in or Like a Tweet without a valid Twitter Kit URL Scheme set up in the app settings. Please see https://dev.twitter.com/twitterkit/ios/installation for more info.' was thrown while invoking logIn on target RNTwitterSignIn with params ( 644, 645 )
```

**Comment by juanlet** [comment]
1)Make sure your twitter url is before the facebook one
2) make sure you put your key after the  -   , from what I´m seeing in your plist you are not respeting this format for that string

 <array>
        <string>twitterkit-312321321312312312</string>
        <string>fb321313123213131</string>
 </array>

**Comment by NathHorrigan** [comment]
Did not fix it :(

This is a section of the plist:
```
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
        	<string>Editor</string>     
			<key>CFBundleURLName</key>
			<string>cointower</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>io.github.cointower</string>
	<string>com.googleusercontent.apps.KEY</string>
				<string>twitterkit-key</string>
				<string>fbKEY</string>
			</array>
		</dict>
	</array>
```

I also just update Twitterkit to 3.3.0 and still no fix

**Comment by NathHorrigan** [comment]
@juanlet Moving the `twitterkit-key` string to the first position of the array gives me the original error of:
```
 [TwitterKit] did encounter error with message "Error obtaining user auth token.": Error Domain=TWTRLogInErrorDomain Code=-1 "<?xml version="1.0" encoding="UTF-8"?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>" UserInfo={NSLocalizedDescription=<?xml version="1.0" encoding="UTF-8"?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>}
```

**Comment by juanlet** [comment]
try to replicate my same setup in the Info.plist and the delegate file....Then check again your settings in twitter apps page. Make sure the bundle id in firebase is the same than in ios project. I will give you the versions of the kit I´m using later

**Comment by NathHorrigan** [comment]
@juanlet Moving `twitterkit-RAND` string to index 0 of array and deactivating callback lock in Twitter Apps fixed it.

**Comment by NathHorrigan** [comment]
Is deactivating twitter lock something that normally needs to happen?

**Comment by Dancyg** [comment]
In the twitter app you created just leave callback URL field empty end uncheck the checkbox "Enable Callback Locking (It is recommended to enable callback locking to ensure apps cannot overwrite the callback url)"

also to eliminate error with TwitterKit - twitterkit string has to go first in info.plist before fb key. Dumb, stupid, idiotic - yeah - it just react-native js framework.
```
<string>twitterkit-1j4IYSwN213123123</string>
<string>fb908123123123123</string>
```

**Comment by Dancyg** [comment]
nope, still
 "Error obtaining user auth token.": Error Domain=TWTRLogInErrorDomain Code=-1 "<?xml version="1.0" encoding="UTF-8"?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings

**Comment by neerajnegidev** [comment]
I have fixed this issue i am using node.js 6.9.5 version and passport js for twitter authentication.
i did below things
1) go to https://apps.twitter.com
2) go to your application app details page then select setting tab.
3) in call back url text box i have entered https://your_domain_name.com/auth/twitter/callback

**Comment by saurabhdtu** [comment]
@smindia1988 Thanks it works. Anyone else facing this issue for android apps or iOS apps can try this.

**Comment by giteekasawlani** [comment]
@smindia1988 I have tried your solution. Its working on iOS but I am still getting error in Android.
I am using Android Gradle
`    implementation 'com.twitter.sdk.android:twitter-core:3.1.1'`

**Comment by omose14** [comment]
Thanks, @smindia1988! You are the best!

**Comment by webmasterdragon** [comment]
@smindia1988 It's working basically.
But firebase twitter authentication does not triggered as like facebook.
How to enable callback URL to firebase twitter auth?

**Comment by maulikdhameliya** [comment]
Thanks @smindia1988 Awesome . Saved my 1 hr

**Comment by Milap-Kundalia** [comment]
I am facing the same issue. I am using firebase for twitter login because twitter SDK is deprecated and discontinued by Twitter. Solution by @smindia1988 is not working in my case.
Let me know if anyone finds any other solution for this.
